### ISSUE TITLE
LaTeX Warning: File `./images/Firefox.jpg' not found on input line 341.

### ISSUE THREAD

**Issue by C138** [genma/Conference_Guide_d_hygiene_numerique#2]
Bonjour,

~/Téléchargements/Git/Conference_Guide_d_hygiene_numerique$ 

pdflatex Genma_Petit_Guide_d_hygiene_numerique.tex

=> LaTeX Warning: File `./images/Firefox.jpg' not found on input line 341.

(mv images/firefox.jpg images/Firefox.jpg)

Bonne continuation

**Comment by genma** [comment]
J'ai pris en compte (normalement). Merci.
